jenkinsci/active-choices-plugin

src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js

Hi,
this tiny change fully supports different input types in the formatted HTML.
Without this change the Formatted HTML option allows to create the various HTML input types dynamically and take a parameter value for the build, but it DOES NOT allow to take the value of such a parameter by a reference to another Reactive Reference Parameters (via Referenced Parameters attribute). 
In effect only the 'input' tag values were reflected. With this change any tag (like select or checkbox will work as well).

Allow for different input types in Formatted HTML

---

src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js

I've found a way to avoid major browser hang when cascade parameter is re-evaluated by a change.
The idea is to pop-up "Loading" screen, and then start actual update operation by firing a timer. It makes browser re-draw and show the "Loading" screen while the script updates actual parameters.
(see https://issues.jenkins-ci.org/browse/JENKINS-34487 for motivation behind the change)
The feature may be browser-specific as it affects the redrawing procedure.
I've tested on Chrome only. (Not sure how to set up the test env for a major testing)
Looking forward for your review and suggestions!
PS. It would be nice to have this functionality be turned on\off in the Jenkins settings. Not sure what should I add to setting-related files to make this happen (never developed jenkins plugins before).

Pop up "Loading..." screen when re-evaluating cascade parameters

---

pom.xml
src/main/java/org/biouno/unochoice/model/ScriptlerScript.java

Other than the 'Scriptler mode', the plugin currently looks reasonable from a security POV, as its embedded scripting uses Script Security.
I haven't done a complete check whether this would be enough to restore distribution (there may be other security issues lurking), but I'd be happy to do that if this change is (tentatively) accepted.
@reviewbybees

Make Scriptler dependency optional

---

pom.xml
src/main/java/org/biouno/unochoice/util/Utils.java

Observed a Jenkins instance freezing up with this in the support bundle:
```
49761msec elapsed in Handling GET /jenkins/job/…/build from "…" : … ParametersDefinitionProperty/index.jelly CascadeChoiceParameter/index.jelly CascadeChoiceParameter/choiceParameterCommon.jelly CascadeChoiceParameter/selectContent.jelly
java.lang.String$CaseInsensitiveComparator.compare(String.java:1186)
java.lang.String.compareToIgnoreCase(String.java:1239)
hudson.util.CaseInsensitiveComparator.compare(CaseInsensitiveComparator.java:40)
hudson.util.CaseInsensitiveComparator.compare(CaseInsensitiveComparator.java:34)
jenkins.model.IdStrategy$CaseInsensitive.compare(IdStrategy.java:176)
jenkins.model.IdStrategy.equals(IdStrategy.java:90)
nectar.plugins.rbac.groups.Group.isMatch(Group.java:493) …
```

Optimizing Utils.findProjectByParameterUUID

---

src/main/java/org/biouno/unochoice/AbstractScriptableParameter.java
src/test/java/org/biouno/unochoice/issue49260/TestProjectDifferenceAcrossFolders.java
src/test/java/org/biouno/unochoice/issue49260/package-info.java

Retrieve project using full name instead of only name to take nested folders into account.
See issue JENKINS-49260 (https://issues.jenkins-ci.org/browse/JENKINS-49260) to have more information about the problem.
A test was added, it fails if you comment out the fullname set, using only project "name". I wrote the test based on previous issues-related tests.

Patch to solve JENKINS-49260

---

src/main/java/org/biouno/unochoice/AbstractScriptableParameter.java
src/test/java/org/biouno/unochoice/issue51296/TestProjectNameAfterRenaming.java
src/test/java/org/biouno/unochoice/issue51296/package-info.java

Retrieve project using UUID in getHelperParameters in case we fail with project name/full name : Typically, when the project is renamed (moved also?)
See issue JENKINS-51296 (https://issues.jenkins-ci.org/browse/JENKINS-51296) to have more information about the problem.
This will make the project being always retrieved by UUID until the AbstractScriptableParameter is modified, performance issue could be solved by removing "final" attribute for projectName and projectFullName and thus, doing a "refresh" of these parameters in case of problem (tried to do so with https://github.com/sebcworks/active-choices-plugin/commit/e697db4aeaa7774c0f9dde699b15596e035a2b18)
A unit test was added as well.

Fix issue JENKINS-51296 getting project after renaming

---

src/main/java/org/biouno/unochoice/AbstractScriptableParameter.java
src/test/java/org/biouno/unochoice/issue61068/TestDefaultValuesOnParamBuildPage.java
src/test/java/org/biouno/unochoice/issue61068/package-info.java

getDefaultParameterValue is used to get value on parambuild and buildWithParameters urls (trigger build). Those pages use text boxes to represent Active Choices parameters.
The method should respect users configuration and return values with ":selected" suffix. If no value contains the suffix, it should return the first element (backward compatibility).

[JENKINS-61068] set correct value on parambuild page

---

README.md
src/main/java/org/biouno/unochoice/AbstractScriptableParameter.java
src/main/java/org/biouno/unochoice/util/Utils.java
src/main/resources/org/biouno/unochoice/common/checkboxContent.jelly
src/main/resources/org/biouno/unochoice/common/radioContent.jelly
src/main/resources/org/biouno/unochoice/common/selectContent.jelly
src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js
src/test/java/org/biouno/unochoice/issue61068/TestDefaultValuesOnParamBuildPage.java
src/test/java/org/biouno/unochoice/util/TestUtils.java

Asked for a new capability derived from https://github.com/jenkinsci/active-choices-plugin/pull/25#issuecomment-601925184.
Allow to disable and select any (select option|radio|checkbox) with :disable and/or :selected

[JENKINS-61751] let :disabled and :deleted at the same time

---

README.md
pom.xml
src/main/java/org/biouno/unochoice/model/ScriptlerScript.java
src/test/java/org/biouno/unochoice/Security470Test.java
src/test/java/org/biouno/unochoice/TestAbstractUnoChoiceParameter.java
src/test/java/org/biouno/unochoice/issue49260/TestProjectDifferenceAcrossFolders.java
src/test/java/org/biouno/unochoice/issue51296/TestProjectNameAfterRenaming.java
src/test/java/org/biouno/unochoice/util/TestUtils.java

Using git-plugin as reference. One major issue is that the build is failing due to hamcrest dependency, coming from powermock.
I think we will need to update to JUnit5, and replace Powermock with... mockito maybe.

[JENKINS-62317]: Upgrade dependencies pre 2.3 release

---

README.md
src/main/java/org/biouno/unochoice/model/GroovyScript.java
src/test/java/org/biouno/unochoice/issue63963/TestGroovyScriptParametersOrder.java
src/test/java/org/biouno/unochoice/jenkins_cert_2008/TestGroovyScriptXssVulnerabilities.java

By default Groovy uses a [LinkedHashMap](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Map.html) (Today-I-Learned!). When we sanitize parameter values that use `Map`'s, we iterate and create a new `HashMap`, causing the elements to be out of order when rendered.

[JENKINS-63963] Use a LinkedHashMap when sanitizing the map (Groovy uses LinkedHashMap by default)

---

src/main/resources/org/biouno/unochoice/common/checkboxContent.jelly
src/main/resources/org/biouno/unochoice/common/radioContent.jelly

Part of the tables-to-divs workaround broke how we calculate the height of radio and check boxes visible. We limit the number of visible items for when users have very long lists.
I wish we had Cypress, and the JS code was more structured, but given it's a major bug, I've done manual testing, and will push a release out today, hoping this fixes the bug and users can start the week upgrading to this latest version.
Cheers
Bruno

[JENKINS-64962] Fix radio buttons and check boxes not displayed (height: 0, css)

---

pom.xml
src/main/java/org/biouno/unochoice/model/ScriptlerScript.java
src/test/java/org/biouno/unochoice/TestPersistingParameters.java
src/test/resources/org/biouno/unochoice/PipelineWithScriptlerParameters.groovy

Add @DataBoundSetters for deprecated properties
As ScriptlerScript previously had a @DataBoundConstructor to help
initialize it with a Scriptler script ID and parameters from a pipeline,
removing those from the constructor gave us no backwards-compatible path
to set these properties. This results in an uninitialized Scriptler
script that we'll call to populate the choices.
Add new @DataBoundSetter methods for accepting these legacy fields and
therefore establish backwards compatibility with versions of Active
Choices prior to 2.6.0. Also add unit tests to ensure that this code
works as expected and will continue to work in the future.
Fixes JENKINS-67934.

Add @DataBoundSetters for deprecated properties

---

src/main/resources/org/biouno/unochoice/CascadeChoiceParameter/index.jelly

since newer jenkins-updates, referenced booelan params stopped working
Fix was posted by Jeremy Cooper in Jira: https://issues.jenkins.io/browse/JENKINS-68013?jql=resolution%20is%20EMPTY%20and%20component%3D20520
I added a second selector to look not only for divs, but also spans in referenced parameters

[JENKINS-68013] fix referencing boolean parameters

---

pom.xml
src/test/java/org/biouno/unochoice/UiAcceptanceTest.java
src/test/resources/test-config.xml

I want to remove the dependency on Prototype so this plugin is compatible with Jenkins 2.401 and above. Before I do that, I want to write an end-to-end test.
See [this post](https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/) for more details on the removal of Prototype.
https://issues.jenkins.io/browse/JENKINS-71365 is the issue for this plugin.
https://github.com/jenkinsci/stapler/pull/452/files shows changes that have been made to stapler which is a dependency of core.
This is a pure test PR. It adds a dependency on `org.seleniumhq.selenium:selenium-java` and relies on `ChromeDriver` to run the actual test. The test works in both headless and normal mode.
The test checks for all 4 kinds of params - `SINGLE_SELECT`, `RADIO`, `CHECKBOX`, `MULTI_SELECT`.
It creates …

test: Add end-to-end tests for UI behavior

---

pom.xml

This allows the tests to use all available cores.
On my M1 MBP, the time to run `mvn verify` went from about `3m52s` to about `53s`.
Only changes are to `pom.xml`.
```[tasklist]
```

chore: Parallelize Unit tests

---

src/test/java/org/biouno/unochoice/jenkins_cert_1954/TestParametersXssVulnerabilities.java

No longer need to check that Jenkins is newer than 2.264 in the test, since Jenkins 2.375.3 or newer is rquired from the pom file.
Tests pass on Linux with Java 11.

Remove outdated Jenkins version test conditional

---

package.json
pom.xml
src/main/resources/org/biouno/unochoice/CascadeChoiceParameter/index.jelly
src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
src/main/resources/org/biouno/unochoice/stapler/unochoice/UnoChoice.es6
src/test/java/org/biouno/unochoice/UiAcceptanceTest.java
webpack.config.js
yarn.lock

The code in `makeStaplerProxy2` used `prototype.js` to create a synchronous version of the standard proxy that comes with Jenkins Core.
This code switches back to the standard proxy.
That requires making the code execute in the correct order when there were dependencies. That is achieved by using `async`/`await` in the `.es6` code and transpiling it down to use Promises so HtmlUnit tests continue to work.
Refs: [JENKINS-71365](https://issues.jenkins.io/browse/JENKINS-71365)
The existing tests pass. The UI Acceptance test was relying on an unexpected side-effect of synchronous network calls.
To account for the network calls becoming asynchronous, the tests now wait for the condition to be successful instead of a straight assert.
```[tasklist]
```

refactor: Replace synchronous proxy with standard proxy

---

src/main/java/org/biouno/unochoice/CascadeChoiceParameter.java
src/main/java/org/biouno/unochoice/ChoiceParameter.java
src/main/java/org/biouno/unochoice/DynamicReferenceParameter.java
src/test/java/org/biouno/unochoice/TestCascadeChoiceParameter.java
src/test/java/org/biouno/unochoice/TestChoiceParameter.java
src/test/java/org/biouno/unochoice/TestDynamicReferenceParameter.java

When using pipelines, people tend to skip `filterable` as a parameter. That causes `filterable` to be set to `null`. Stapler would emit an empty string.
The prior behavior used javascript truthiness and treated it as `false`.
Since moving almost all javascript into separate files, the new behavior causes an empty string to be printed during the method call.
This change guarantees we emit a primitive `boolean` instead of a boxed `Boolean`.
Refs: [JENKINS-71724](https://issues.jenkins.io/browse/JENKINS-71724)
Added new tests.
Existing tests pass.
```[tasklist]
```

fix: When configured using a pipeline, handle null filterable

---

CHANGES.md
src/main/java/org/biouno/unochoice/CascadeChoiceParameter.java
src/main/java/org/biouno/unochoice/ChoiceParameter.java
src/main/java/org/biouno/unochoice/DynamicReferenceParameter.java
src/main/java/org/biouno/unochoice/model/GroovyScript.java
src/main/java/org/biouno/unochoice/model/ScriptlerScript.java
src/main/webapp/help/parameter/active-choices-cascade-choice.html
src/main/webapp/help/parameter/active-choices-choice.html
src/main/webapp/help/parameter/active-choices-dynamic-reference-parameter.html
src/test/java/org/biouno/unochoice/UiAcceptanceTest.java

Supersedes #43 
```[tasklist]
```

[JENKINS-65813] Add @Symbol to support pipeline

---

src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
src/main/resources/org/biouno/unochoice/common/choiceParameterCommon.jelly
src/main/resources/org/biouno/unochoice/stapler/unochoice/UnoChoice.es6
src/test/java/org/biouno/unochoice/UiAcceptanceTest.java
src/test/java/org/biouno/unochoice/jenkins_cert_1954/TestParametersXssVulnerabilities.java

This PR show a waiting spinner at the beginning of update parameter method and hide it at the end.  
I am not totally satisfy about the spinner position (other item's positions are impacted by visibility changes) but my js-knowledge is not good enough to make it better.  
I use this pipeline to test the wanted comportement.  
```groovy
properties([
parameters([
[
name: 'States',
$class: 'ChoiceParameter',
choiceType: 'PT_SINGLE_SELECT',
description: 'Choose a state',
script: [
$class: 'GroovyScript',
script: [sandbox:false, script: '''return ['Sao Paulo','Rio de Janeiro','Parana','Acre']''']
]
],
[
name: 'Cities',
$class: 'CascadeChoiceParameter',
choiceType: 'PT_SINGLE_SELECT',
referencedParameters: 'States',
description: 'Choose a city',
script: [
$class: 'GroovyScript',
script: …
```

JENKINS-72213 : Add a waiting spinner during parameter building

---

CHANGES.md
src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly

This PR fix an unseen exception (introduced with #163) when multiple dynamique reference parameters are used at the same time.  
In jelly file, var keyword must be used instead of let.
source : https://issues.jenkins.io/browse/JENKINS-72936
```[tasklist]
```

[JENKINS-72936]: Fix index.jelly for DynamicReferenceParameter

---

src/main/resources/org/biouno/unochoice/ChoiceParameter/index.jelly
src/main/resources/org/biouno/unochoice/ChoiceParameter/render-choice-parameter.js

https://issues.jenkins.io/browse/JENKINS-74030
Created a freestyle project with 2 Active Choices Parameters. Took sample Groovy scripts from the README. It's important to check **Enable filters** so that the script is included into the page.
[Before the change](https://www.youtube.com/watch?v=D5wJv7zqFtM)
[After the change](https://www.youtube.com/watch?v=8li82MbNDn0)

[JENKINS-74030] Extract inline script from `ChoiceParameter/index.jelly`

---

src/main/resources/org/biouno/unochoice/common/choiceParameterCommon.jelly
src/main/resources/org/biouno/unochoice/common/multi-select.js

https://issues.jenkins.io/browse/JENKINS-74028
Created a freestyle project with 2 Active Choices Parameters. Took sample Groovy scripts from the README. Choice type - Multi Select.
[Before the change](https://www.youtube.com/watch?v=mTO-2CSgB0I)
[After the change](https://www.youtube.com/watch?v=-JL5p6gcvjA)
P.S. On the **After the change** video you'll see CSP violations in the report. Those aren't related to this change, and are fixed in https://github.com/jenkinsci/active-choices-plugin/pull/371. The reason they didn't appear on the **Before** video is because it was recorded with the plugin version built from https://github.com/jenkinsci/active-choices-plugin/pull/371.

[JENKINS-74028] Extract inline script from `choiceParameterCommon.jelly`

---

src/main/resources/org/biouno/unochoice/common/checkbox-content.js
src/main/resources/org/biouno/unochoice/common/checkboxContent.jelly

https://issues.jenkins.io/browse/JENKINS-74025
Created a freestyle project with 2 Active Choices Parameters. Took sample Groovy scripts from the README. Choice type - Check Boxes.
[Before the change](https://www.youtube.com/watch?v=IN8uSIe36T8)
[After the change](https://www.youtube.com/watch?v=bvr7V64ot2M)

[JENKINS-74025] Extract inline JavaScript from `checkboxContent.jelly`

---

src/main/resources/org/biouno/unochoice/CascadeChoiceParameter/cascade-choice-parameter.js
src/main/resources/org/biouno/unochoice/CascadeChoiceParameter/index.jelly
src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/dynamic-reference-parameter.js
src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
src/test/java/org/biouno/unochoice/jenkins_cert_2008/TestGroovyScriptXssVulnerabilities.java

- Extract inline JavaScript from `DynamicReferenceParameter/index.jelly`
- Extract inline JavaScript from `CascadeChoiceParameter/index.jelly`
https://issues.jenkins.io/browse/JENKINS-74026
https://issues.jenkins.io/browse/JENKINS-74027
I've relied a lot on the scenario from https://issues.jenkins.io/browse/JENKINS-71909. Made sure that isn't broken. Unit test that asserts that behavior is very much appreciated, helped me a lot along the way. I feel like I'm almost over relying on it though.
[Before the fix](https://www.youtube.com/watch?v=uctGEYAXXYY)
[After the fix](https://www.youtube.com/watch?v=GCH3wqcMHUk)

[JENKINS-74026][JENKINS-74027] Improve CSP compatibility

---

src/main/resources/org/biouno/unochoice/common/radio-content.js
src/main/resources/org/biouno/unochoice/common/radioContent.jelly

https://issues.jenkins.io/browse/JENKINS-74029
Created a freestyle project with 2 Active Choices Parameters. Took sample Groovy scripts from the README. Choice type - Radio Buttons.
[Before the change](https://www.youtube.com/watch?v=zyDrLcfCcgc)
[After the change](https://www.youtube.com/watch?v=ko1e0stsWXM)

[JENKINS-74029] Extract inline JavaScript from `radioContent.jelly`

---

src/main/js/UnoChoice.es6
src/test/java/org/biouno/unochoice/issue62835/TestForNodeLabelParameter.java
src/test/java/org/biouno/unochoice/issue63963/TestGroovyScriptParametersOrder.java
src/test/java/org/biouno/unochoice/issue71909/TestRevertingAsynchronousProxy.java
src/test/resources/org/biouno/unochoice/issue71909/TestRevertingAsynchronousProxy/test/jobs/test/config.xml

https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback
Maybe we could rewrite the plug-in some day to use the DOM monitor, but that'd probably break jobs that use Timers/Pipelines (which we never intended to officially support, but since the plug-in works in that cases under certain conditions, there's no need to break it for now).
Tested locally and the plug-in updated the parameters in the expected order. This really needs more users to help here.

[JENKINS-75194] Use window.requestIdleCallback instead of setTimeout to force the browser to update parameters in order, waiting for DOM to be updated

---

src/main/java/org/biouno/unochoice/UnoChoiceParameterDescriptor.java
src/main/java/org/biouno/unochoice/model/AbstractScript.java
src/main/java/org/biouno/unochoice/model/Script.java
src/main/java/org/biouno/unochoice/model/ScriptDescriptor.java

Since this is used as the declared type of a nested field in higher `Describable`s, https://github.com/jenkinsci/active-choices-plugin/blob/59bda8415ce02e07125e1aa350e26f6be4bee9ed/src/main/java/org/biouno/unochoice/CascadeChoiceParameter.java#L125-L126 for example, it is mandatory to show that it is `Describable`.

Implement `Describable` from `Script`, not `AbstractScript`
