jenkinsci/active-choices-plugin

pom.xml

I've updated some old URLs.
What do you think @kinow?

Updated some old URLs

---

src/main/java/org/biouno/unochoice/model/ScriptlerScript.java

Worked locally, will prepare a release if no local tests fail.

Remove methods using scriptler classes directly to keep dependency optional

---

README.md

Remove Roadmap section

---

src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js

a possible fix for: https://issues.jenkins.io/browse/JENKINS-65096

[JENKINS-6509] - Fix Active Choice Reactive Parameter rendering with Jenkins 2.277.1

---

src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js

- additional changes to https://github.com/jenkinsci/active-choices-plugin/pull/45
- FIX for some tasks the html already contains the element list, in that case the javascript filled the elements under the first element, practically creating them as additional elements. I still does not understand why for some similar tasks there are pre-generated values for others just error values and then the right values will get filled via javascript.
- added a few more if's for backward compatibility (was not tested with jenkins < 2.277.1)
- added the class "tr" to tr like div elements to match the pre-filled elements (from jelly templates), not all element type was tested

Additional fix for: JENKINS-65096

---

README.md
pom.xml
src/main/java/org/biouno/unochoice/model/ScriptlerScript.java
src/test/java/org/biouno/unochoice/issue63983/TestSandboxAndApproval.java
src/test/java/org/biouno/unochoice/issue63983/package-info.java
src/test/resources/org/biouno/unochoice/issue63983/TestSandboxAndApproval/README.md
src/test/resources/org/biouno/unochoice/issue63983/TestSandboxAndApproval/config.xml
src/test/resources/org/biouno/unochoice/issue63983/TestSandboxAndApproval/users/admin/config.xml
src/test/resources/org/biouno/unochoice/issue63983/TestSandboxAndApproval/users/summerworkers/config.xml

Tested with a Scriptler script containing the @Grapes annotation using Jenkins 2.289.2.

Fix for JENKINS-63983

---

pom.xml
src/main/java/org/biouno/unochoice/model/ScriptlerScript.java
src/main/resources/org/biouno/unochoice/CascadeChoiceParameter/index.jelly
src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js
src/test/java/org/biouno/unochoice/issue62835/TestForNodeLabelParameter.java
src/test/java/org/biouno/unochoice/issue62835/package-info.java

Just needs manual testing, and then confirm whether it's possible to have a unit or functional test added.
If it's all working, we can include it in the next release — coming in the next days. :crossed_fingers:

[JENKINS-62835] If no input element found for referenced parameter, try an input element, whose name is not name, and not empty

---

src/main/resources/org/biouno/unochoice/common/choiceParameterCommon.jelly
src/main/resources/org/biouno/unochoice/stapler/unochoice.jelly

[JENKINS-66853] Use CSS flex for parameter div

---

pom.xml
src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/index.jelly
src/main/resources/org/biouno/unochoice/stapler/unochoice/unochoice.js
src/test/java/org/biouno/unochoice/TestPersistingParameters.java
src/test/java/org/biouno/unochoice/issue63983/TestSandboxAndApproval.java
src/test/java/org/biouno/unochoice/jenkins_cert_1954/TestParametersXssVulnerabilities.java

Update dependencies and check reactive parameters with newer Jenkins versions

---

.gitignore

Sync with BioUno repo of active choices. No code updates

---

src/main/java/org/biouno/unochoice/AbstractScriptableParameter.java
src/test/java/org/biouno/unochoice/issue69448/TestDefaultValuesWithScriptReturningMap.java
src/test/java/org/biouno/unochoice/issue69448/package-info.java

Fixes JENKINS-69448

---

README.md

Fix badge links, and update bom version

---

src/test/java/org/biouno/unochoice/TestPersistingParameters.java
src/test/java/org/biouno/unochoice/issue63983/TestSandboxAndApproval.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/MtR7dypUE?organizationId=SmVua2lucyBDSQ%3D%3D

refactor: Java Security Ultimate Scan 2023

---

pom.xml
src/main/java/org/biouno/unochoice/model/ScriptlerScript.java
src/test/java/org/biouno/unochoice/issue72105/TestJobDslWithScriptlerScriptWithParameters.java
src/test/java/org/biouno/unochoice/issue72105/package-info.java
src/test/resources/org/biouno/unochoice/issue72105/TestJobDslWithScriptlerScriptWithParameters/test/jobs/job/config.xml

- [JENKINS-72105](https://issues.jenkins.io/browse/JENKINS-72105)
- When there is no `parameters`(deprecated param) in `scriptlerScript`, `parameters` is set with `Collections.emptyMap()`. And it is not null, so `parameters` and `parameters` in `ScriptlerBuilder` in `initializeFromDeprecatedProperties` is empty map and so parameter can't created.
- I tested with snapshot version of scriptler-plugin, but I don't know the new version of scriptler dependency is mandatory. So I create commit without pom.xml.
- ![image](https://github.com/jenkinsci/active-choices-plugin/assets/16630665/c67f4dfa-a9f6-43d4-b25d-29d2511bf637)
```[tasklist]
```

[JENKINS-72105] Fix scriptler script's parameter

---

Jenkinsfile

Updated to follow [archetypes]( https://github.com/jenkins-infra/pipeline-library/)
```[tasklist]
```

Test with jdk-17 on windows and jdk-21 on linux

---

src/main/java/org/biouno/unochoice/model/GroovyScript.java
src/main/java/org/biouno/unochoice/util/Utils.java

Adapting to https://github.com/jenkinsci/jenkins/pull/4604 in this plugin.
`mvn clean verify -Dtest=InjectedTest`

Replace EOL JSR 305 annotations with SpotBugs annotations

---

Jenkinsfile
src/main/java/org/biouno/unochoice/AbstractCascadableParameter.java
src/main/java/org/biouno/unochoice/AbstractScriptableParameter.java
src/main/java/org/biouno/unochoice/DynamicReferenceParameter.java
src/test/java/org/biouno/unochoice/BaseUiTest.java

Fix IDE warnings and disable pipeline for Windows (broken selenium WebDriver?)

---

src/main/java/org/biouno/unochoice/AbstractScriptableParameter.java
src/main/java/org/biouno/unochoice/AbstractUnoChoiceParameter.java
src/main/java/org/biouno/unochoice/DynamicReferenceParameter.java
src/test/java/org/biouno/unochoice/TestAbstractUnoChoiceParameter.java

Migrate from deprecated EE 8 methods to EE 9 equivalents.

Migrate from EE 8 to EE 9

---

src/main/java/org/biouno/unochoice/util/Utils.java

Migrate from deprecated Acegi compatibility layer to non-deprecated Spring Security equivalents.
`mvn clean verify -Dtest=InjectedTest`

Migrate from Acegi to Spring Security

---

src/test/java/org/biouno/unochoice/BaseUiTest.java
src/test/java/org/biouno/unochoice/Security470Test.java
src/test/java/org/biouno/unochoice/TestAbstractUnoChoiceParameter.java
src/test/java/org/biouno/unochoice/TestCascadeChoiceParameter.java
src/test/java/org/biouno/unochoice/TestChoiceParameter.java
src/test/java/org/biouno/unochoice/TestDynamicReferenceParameter.java
src/test/java/org/biouno/unochoice/TestParametersOrder.java
src/test/java/org/biouno/unochoice/TestPersistingParameters.java
src/test/java/org/biouno/unochoice/UiAcceptanceTest.java
src/test/java/org/biouno/unochoice/issue34818/TestGlobalNodePropertiesScript.java
src/test/java/org/biouno/unochoice/issue38532/TestParameterValuesWithEquals.java
src/test/java/org/biouno/unochoice/issue48448/TestParameterObjectIsPresent.java
src/test/java/org/biouno/unochoice/issue49260/TestProjectDifferenceAcrossFolders.java
src/test/java/org/biouno/unochoice/issue51296/TestProjectNameAfterRenaming.java
src/test/java/org/biouno/unochoice/issue61068/TestDefaultValuesOnParamBuildPage.java
src/test/java/org/biouno/unochoice/issue62215/TestMarkupFormatterAllowsRequiredElementsInScriptOutput.java
src/test/java/org/biouno/unochoice/issue62835/TestForNodeLabelParameter.java
src/test/java/org/biouno/unochoice/issue63963/TestGroovyScriptParametersOrder.java
src/test/java/org/biouno/unochoice/issue63983/TestSandboxAndApproval.java
src/test/java/org/biouno/unochoice/issue65235/TestProjectObjectIsPresentOnMultibranchWorkflow.java
src/test/java/org/biouno/unochoice/issue69448/TestDefaultValuesWithScriptReturningMap.java
src/test/java/org/biouno/unochoice/issue71909/TestRevertingAsynchronousProxy.java
src/test/java/org/biouno/unochoice/issue72105/TestJobDslWithScriptlerScriptWithParameters.java
src/test/java/org/biouno/unochoice/jenkins_cert_1954/TestParametersXssVulnerabilities.java
src/test/java/org/biouno/unochoice/jenkins_cert_2008/TestGroovyScriptXssVulnerabilities.java
src/test/java/org/biouno/unochoice/jenkins_cert_2192/TestDynamicReferenceXss.java
src/test/java/org/biouno/unochoice/jenkins_cert_2219/TestXssParameterNameBrowserConsole.java
src/test/java/org/biouno/unochoice/util/TestScriptCallback.java
src/test/java/org/biouno/unochoice/util/TestUtils.java
src/test/java/org/jenkinsci/plugins/scriptler/ScriptlerHelper.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
There is one exception where a migration was not possible as the tests rely on `Rule` implementations that have not (yet) been migrated to JUnit5:
* `TestProjectObjectIsPresentOnMultibranchWorkflow` using `GitSampleRepoRule`
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5

---

src/test/java/org/biouno/unochoice/issue65235/TestProjectObjectIsPresentOnMultibranchWorkflow.java

In #443 I said that `TestProjectObjectIsPresentOnMultibranchWorkflow` could not be migrated to JUnit5 as it is using `GitSampleRepoRule`. Turns out I was wrong about that and thanks to https://github.com/jenkinsci/git-plugin/pull/1574 it can be made compatible with JUnit5 as well.
`mvn clean verify`

Migrate GitSampleRepoRule to JUnit5

---

CHANGES.md
src/main/js/UnoChoice.es6
src/test/java/org/biouno/unochoice/issue74967/TestFilter.java
src/test/java/org/biouno/unochoice/issue74967/package-info.java
src/test/resources/org/biouno/unochoice/issue74967/TestFilter/test/jobs/test/config.xml

JENKINS-74967: Fix JS error when using the filter

---

CHANGES.md
src/main/resources/org/biouno/unochoice/CascadeChoiceParameter/cascade-choice-parameter.js
src/main/resources/org/biouno/unochoice/DynamicReferenceParameter/dynamic-reference-parameter.js
src/test/java/org/biouno/unochoice/BaseUiTest.java
src/test/java/org/biouno/unochoice/issue71909/TestRevertingAsynchronousProxy.java
src/test/java/org/biouno/unochoice/issue73239/TestCascadeParameterIsEmpty.java
src/test/java/org/biouno/unochoice/issue73239/package-info.java
src/test/java/org/biouno/unochoice/util/PrintAllWebConsolerLogger.java
src/test/resources/org/biouno/unochoice/issue73239/TestCascadeParameterIsEmpty/test/jobs/test/config.xml

Prevent JS errors when there are no referenced parameters. Unit tests included, and making another test less brittle.

JENKINS-73239 Prevent JS errors when there are no referenced parameters

---

src/test/java/org/biouno/unochoice/issue71909/TestRevertingAsynchronousProxy.java

See https://github.com/jenkinsci/active-choices-plugin/pull/479#pullrequestreview-2775535035

Fix Stale exception (selenium) in test

---

CHANGES.md
src/main/js/UnoChoice.es6

JENKINS-75596: Add polyfill for window.requestIdleCallback for Safari

---

CHANGES.md
pom.xml

For https://github.com/jenkinsci/active-choices-plugin/pull/532

Update to Jenkins 2.504.1
